version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: magento2opensearch
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
      - "http.host=0.0.0.0"
      - "http.port=9200"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx${M2D_OPENSEARCH_MAX_HEAP_SIZE:-512m}"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disable demo config see https://opensearch.org/docs/latest/opensearch/install/docker-security/
    ports:
      - "9200:9200"
networks:
  default:
    name: env_default
    external: true
